# Generated by Django 3.2.16 on 2022-11-24 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garbage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='垃圾桶编号')),
                ('place', models.CharField(max_length=64, verbose_name='垃圾桶地址')),
                ('class_1', models.FloatField(default=0, verbose_name='可回收垃圾')),
                ('class_2', models.FloatField(default=0, verbose_name='有害垃圾')),
                ('class_3', models.FloatField(default=0, verbose_name='餐厨垃圾')),
                ('class_4', models.FloatField(default=0, verbose_name='其他垃圾')),
                ('totle', models.FloatField(default=0, verbose_name='当前总量')),
                ('max_size', models.FloatField(default=50, verbose_name='阈值')),
                ('longitude', models.CharField(default='0', max_length=32, verbose_name='经度')),
                ('latitude', models.CharField(default='0', max_length=32, verbose_name='纬度')),
            ],
            options={
                'unique_together': {('longitude', 'latitude')},
            },
        ),
        migrations.CreateModel(
            name='Statictics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('class_1', models.FloatField(default=0, verbose_name='可回收垃圾')),
                ('class_2', models.FloatField(default=0, verbose_name='有害垃圾')),
                ('class_3', models.FloatField(default=0, verbose_name='餐厨垃圾')),
                ('class_4', models.FloatField(default=0, verbose_name='其他垃圾')),
            ],
        ),
        migrations.CreateModel(
            name='UserGrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('grade', models.IntegerField(verbose_name='积分')),
            ],
        ),
        migrations.CreateModel(
            name='OneStatictics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('class_1', models.FloatField(default=0, verbose_name='可回收垃圾')),
                ('class_2', models.FloatField(default=0, verbose_name='有害垃圾')),
                ('class_3', models.FloatField(default=0, verbose_name='餐厨垃圾')),
                ('class_4', models.FloatField(default=0, verbose_name='其他垃圾')),
                ('garbage', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='index.garbage', verbose_name='ID')),
            ],
            options={
                'unique_together': {('garbage', 'date')},
            },
        ),
    ]
